# Generated by Django 3.2 on 2021-04-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210418_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorVariant',
        ),
    ]
