# Generated by Django 3.2 on 2021-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_color_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
