# Generated by Django 3.2 on 2021-04-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_variants_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='title',
        ),
    ]
