# Generated by Django 3.2 on 2021-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='reference',
            field=models.TextField(),
        ),
    ]
