# Generated by Django 3.2 on 2021-04-14 17:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshopApp', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumbnail', models.ImageField(upload_to='image/')),
                ('video_link', models.URLField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=50)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('award_wining', models.PositiveIntegerField(default=0)),
                ('project_done', models.PositiveIntegerField(default=0)),
                ('event', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='default.jpg', upload_to='team/')),
            ],
        ),
    ]
