# Generated by Django 3.2 on 2021-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshopApp', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
