# Generated by Django 3.2 on 2021-04-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshopApp', '0006_slider_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='smptserver',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
