# Generated by Django 3.2 on 2021-04-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0004_auto_20210418_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderproduct',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
